package com.andersontoolinginc.fbgrabber;

public enum EquipmentCategories {
    VERTICAL_LATHES,
    VERTICAL_BORING_MILLS,
    SURFACE_GRINDERS,
    RADIAL_DRILLS,
    PRESS,
    POST_DRILL_PRESSES,
    CNC_LATHES,
    CARBIDE_MILLING_INSERT,
    BORING_MACHINES,
    CNC_MACHINING_CENTERS,
    HORIZONTAL_BORING_MILLS,
    MISCELLANEOUS_EQUIPMENT_AND_MACHINES,
    MANUAL_MILLING_MACHINES,
    KNEE_MILLS,
    BAND_SAWS,
    ENGINE_LATHES
}
